### ISSUE TITLE
Build failed: No such file or directory (os error 2), src/libcore/result.rs:997:5

### ISSUE THREAD

**Issue by gqqnbig** [flxo/rogcat#20]
I build the project on Ubuntu 18.04. I installed Rust by running 

`curl https://sh.rustup.rs -sSf | sh`

then run 

`RUST_BACKTRACE=1 cargo install --path .`

I get this error

```
  Installing rogcat v0.3.1-alpha.0 (/home/gqqnbig/Project/rogcat)
   Compiling libudev-sys v0.1.4
   Compiling tokio-current-thread v0.1.4
   Compiling idna v0.1.5
   Compiling parking_lot_core v0.3.1
   Compiling rand_chacha v0.1.0
   Compiling rand_pcg v0.1.1
   Compiling rand v0.6.1
   Compiling rand v0.5.5
error: failed to run custom build command for `libudev-sys v0.1.4`
process didn't exit successfully: `/home/gqqnbig/Project/rogcat/target/release/build/libudev-sys-364e8e627474c66d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"`: No such file or directory (os error 2)"', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: main
  15: __libc_start_main
  16: _start

warning: build failed, waiting for other jobs to finish...
error: failed to compile `rogcat v0.3.1-alpha.0 (/home/gqqnbig/Project/rogcat)`, intermediate artifacts can be found at `/home/gqqnbig/Project/rogcat/target`

Caused by:
  build failed
```

How do I build it properly?

**Comment by flxo** [comment]
Hi,

you're missing the `udev` headers that are required to build `libudev-sys`. Please check [the Dependency section](https://github.com/dcuddeback/libudev-sys) of `libudev-sys.

cheers,

flxo

**Comment by gqqnbig** [comment]
I installed libudev-dev, but still fail.

```
[12:13:10]->~/Project/rogcat$ sudo apt-get install libudev-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libudev-dev is already the newest version (237-3ubuntu10.21).
0 upgraded, 0 newly installed, 0 to remove and 378 not upgraded.
[12:13:46]->~/Project/rogcat$ cargo install --path .
  Installing rogcat v0.3.1-alpha.0 (/home/gqqnbig/Project/rogcat)
   Compiling libudev-sys v0.1.4
   Compiling clicolors-control v0.3.0
   Compiling time v0.1.40
   Compiling term_size v0.3.1
   Compiling directories v1.0.2
   Compiling crossbeam-deque v0.6.2
error: failed to run custom build command for `libudev-sys v0.1.4`
process didn't exit successfully: `/home/gqqnbig/Project/rogcat/target/release/build/libudev-sys-364e8e627474c66d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"`: No such file or directory (os error 2)"', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `rogcat v0.3.1-alpha.0 (/home/gqqnbig/Project/rogcat)`, intermediate artifacts can be found at `/home/gqqnbig/Project/rogcat/target`

Caused by:
  build failed
```

**Comment by drahnr** [comment]
Can you post the output of `pkg-config --libs --cflags libudev` and `which pkg-config`

**Comment by gqqnbig** [comment]
I didn't have pkg-config. After installing it, I can compile. Thanks.
