### ISSUE TITLE
Panic on early log message

### ISSUE THREAD

**Issue by sjuxax** [flxo/rogcat#51]
I try to run rogcat like so, and get this backtrace:

```
❯ RUST_BACKTRACE=full rogcat --level=info -f human
14:00:07.318 snet_event_log                     (498 498)  I    [121035042,-1,]
14:00:07.327 auditd                             (498 498)  I    Multiple same specifications for vendor.google.wireless_charger.IWirelessCharger/default.
14:00:07.327 auditd                             (498 498)  I    SELinux: Loaded service context from:
14:00:07.327 auditd                             (498 498)  I    /system/etc/selinux/plat_service_contexts
14:00:07.327 auditd                             (498 498)  I    /system_ext/etc/selinux/system_ext_service_contexts
14:00:07.327 auditd                             (498 498)  I    /product/etc/selinux/product_service_contexts
14:00:07.327 auditd                             (498 498)  I    /vendor/etc/selinux/vendor_service_contexts
thread 'tokio-runtime-worker-0' panicked at src/terminal.rs:183:57:
Date format error: InvalidMonth
stack backtrace:
   0:     0x59720069cc2a - std::backtrace_rs::backtrace::libunwind::trace::hf44ff866f36f5b0e
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x59720069cc2a - std::backtrace_rs::backtrace::trace_unsynchronized::h7e766ece10137971
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x59720069cc2a - std::sys::backtrace::_print_fmt::h353835d088745806
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/backtrace.rs:66:9
   3:     0x59720069cc2a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h85a9257eb6c41e04
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/backtrace.rs:39:26
   4:     0x5972006c541b - core::fmt::rt::Argument::fmt::h6f690103f6b5b0a0
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/fmt/rt.rs:177:76
   5:     0x5972006c541b - core::fmt::write::hcc8bee8d21353e39
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/fmt/mod.rs:1178:21
   6:     0x597200698a03 - std::io::Write::write_fmt::h70ac935b0c89b059
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/io/mod.rs:1823:15
   7:     0x59720069ca72 - std::sys::backtrace::BacktraceLock::print::hd262bc6f83870824
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/backtrace.rs:42:9
   8:     0x59720069dd37 - std::panicking::default_hook::{{closure}}::h1ac01a4d50ceb64f
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:268:22
   9:     0x59720069db66 - std::panicking::default_hook::h7c4ba54603c1d0b3
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:295:9
  10:     0x59720069e377 - std::panicking::rust_panic_with_hook::h0dd05eda4407feb9
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:801:13
  11:     0x59720069e217 - std::panicking::begin_panic_handler::{{closure}}::hff4951198a9049be
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:674:13
  12:     0x59720069d109 - std::sys::backtrace::__rust_end_short_backtrace::hae232f20e82e2c44
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/backtrace.rs:170:18
  13:     0x59720069dea4 - rust_begin_unwind
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:665:5
  14:     0x5972006c2dc3 - core::panicking::panic_fmt::h6dddd3310fdcb8b7
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/panicking.rs:74:14
  15:     0x5972006c31a6 - core::result::unwrap_failed::h71812c0dbd0b483b
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/result.rs:1689:5
  16:     0x597200358d40 - core::result::Result<T,E>::expect::h8d4dbabf9bfddd6a
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/result.rs:1059:23
  17:     0x597200358d40 - rogcat::terminal::Human::print::hd7e4b276e6fbca91
                               at /home/jeff/local_clones/github.com/flxo/rogcat/src/terminal.rs:183:30
  18:     0x597200358d40 - <rogcat::terminal::Human as futures::sink::Sink>::start_send::hd4685cfaedea8543
                               at /home/jeff/local_clones/github.com/flxo/rogcat/src/terminal.rs:399:9
  19:     0x597200342b8d - <alloc::boxed::Box<S> as futures::sink::Sink>::start_send::ha37302b61c967123
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/sink/mod.rs:64:13
  20:     0x597200342b8d - <futures::sink::map_err::SinkMapErr<S,F> as futures::sink::Sink>::start_send::hdf46fc7e85b1c51c
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/sink/map_err.rs:45:9
  21:     0x59720039edf0 - <alloc::boxed::Box<S> as futures::sink::Sink>::start_send::ha37302b61c967123
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/sink/mod.rs:64:13
  22:     0x59720039edf0 - futures::stream::forward::Forward<T,U>::try_start_send::habde1ee09f8c9f1c
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/stream/forward.rs:67:44
  23:     0x59720039f296 - <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll::h2c7ba4dfdbaad992
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/stream/forward.rs:98:56
  24:     0x59720035d73e - <futures::future::map::Map<A,F> as futures::future::Future>::poll::hdba999f968959d5f
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/future/map.rs:30:23
  25:     0x597200387575 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h2cf6793782afed85
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/future/map_err.rs:30:23
  26:     0x59720036a22f - <futures::sync::oneshot::Execute<F> as futures::future::Future>::poll::h0fd4cd35e7afca3f
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/sync/oneshot.rs:589:28
  27:     0x59720060120b - <alloc::boxed::Box<F> as futures::future::Future>::poll::h9db2e10985b2be07
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/future/mod.rs:113:13
  28:     0x59720060120b - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h99dd783ccd41a461
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/mod.rs:329:45
  29:     0x59720060120b - futures::task_impl::Spawn<T>::enter::{{closure}}::h0f87ea334103ee3b
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/mod.rs:399:27
  30:     0x59720060120b - futures::task_impl::std::set::h2951a79e28cf56dd
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/std/mod.rs:86:13
  31:     0x597200601bf8 - futures::task_impl::Spawn<T>::enter::h7884d65de83cde0a
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/mod.rs:399:9
  32:     0x597200601bf8 - futures::task_impl::Spawn<T>::poll_fn_notify::hf1e1d4047f5ef0fc
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/mod.rs:291:14
  33:     0x597200601bf8 - futures::task_impl::Spawn<T>::poll_future_notify::hfc6a679e00a071fb
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-0.1.31/src/task_impl/mod.rs:329:9
  34:     0x597200601bf8 - tokio_threadpool::task::Task::run::{{closure}}::h07f0e6f3c42c8c30
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/task/mod.rs:147:22
  35:     0x597200601bf8 - core::ops::function::FnOnce::call_once::hfde19780deaa032e
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/ops/function.rs:250:5
  36:     0x597200601bf8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb9f5758042f79da1
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/panic/unwind_safe.rs:272:9
  37:     0x597200601bf8 - std::panicking::try::do_call::he39481fadaffb1ab
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:557:40
  38:     0x597200601bf8 - std::panicking::try::h3faec5aaddcbe41e
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:520:19
  39:     0x597200601bf8 - std::panic::catch_unwind::hd20552343115ec1d
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panic.rs:345:14
  40:     0x597200601bf8 - tokio_threadpool::task::Task::run::h8619a1806f518e36
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/task/mod.rs:130:19
  41:     0x5972005f7212 - tokio_threadpool::worker::Worker::run_task2::ha5ec5b5f7512ebfc
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:567:9
  42:     0x5972005f7212 - tokio_threadpool::worker::Worker::run_task::ha7bfa356bc2906f9
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:459:19
  43:     0x5972005f664d - tokio_threadpool::worker::Worker::try_run_owned_task::h19c56b9f4d4a5049
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:390:17
  44:     0x5972005f664d - tokio_threadpool::worker::Worker::try_run_task::h8574dfc68fd77f41
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:297:12
  45:     0x5972005f664d - tokio_threadpool::worker::Worker::run::h874fc381efdc7804
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:241:21
  46:     0x5972005e494c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h54970672b1d0c084
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-0.1.22/src/runtime/threadpool/builder.rs:390:29
  47:     0x5972005e494c - tokio_timer::timer::handle::with_default::h4c243608ec0e5cf8
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-timer-0.2.13/src/timer/handle.rs:74:5
  48:     0x5972005e494c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::he5be6d55c281621a
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-0.1.22/src/runtime/threadpool/builder.rs:382:25
  49:     0x5972005e494c - tokio_timer::clock::clock::with_default::hb8bbca7132021c92
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-timer-0.2.13/src/clock/clock.rs:125:5
  50:     0x5972005df4f5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::h7a631f9b62f5e7d6
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-0.1.22/src/runtime/threadpool/builder.rs:381:21
  51:     0x5972005df4f5 - tokio_reactor::with_default::hfc453d32d6df1d44
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-reactor-0.1.12/src/lib.rs:220:5
  52:     0x5972005df4f5 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h1ba69bd0a3ed78f9
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-0.1.22/src/runtime/threadpool/builder.rs:380:17
  53:     0x5972005f6167 - tokio_threadpool::callback::Callback::call::hb12961516c2fc74f
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/callback.rs:22:9
  54:     0x5972005f6167 - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::ha2da1c252080cebd
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:127:21
  55:     0x5972005f6167 - tokio_executor::global::with_default::{{closure}}::hb11b1d8fcb5f73c3
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-executor-0.1.10/src/global.rs:221:9
  56:     0x5972005f6167 - std::thread::local::LocalKey<T>::try_with::h21862f4b87602f39
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/local.rs:283:12
  57:     0x5972005f6167 - std::thread::local::LocalKey<T>::with::h47a2a0ecd1df66dc
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/local.rs:260:9
  58:     0x5972005f6167 - tokio_executor::global::with_default::h64d8888f40a9c1a6
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-executor-0.1.10/src/global.rs:190:14
  59:     0x5972005f6167 - tokio_threadpool::worker::Worker::do_run::{{closure}}::hbce41e94aeb7df99
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:125:13
  60:     0x5972005f6167 - std::thread::local::LocalKey<T>::try_with::hce292e347a7e239b
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/local.rs:283:12
  61:     0x5972005f6167 - std::thread::local::LocalKey<T>::with::hdb7ecc6cb2ba4747
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/local.rs:260:9
  62:     0x5972005f6167 - tokio_threadpool::worker::Worker::do_run::hd0d80b110aa34823
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/worker/mod.rs:116:24
  63:     0x5972005fc23d - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h4c807f4019a9c15b
                               at /home/jeff/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-threadpool-0.1.18/src/pool/mod.rs:345:21
  64:     0x5972005fc23d - std::sys::backtrace::__rust_begin_short_backtrace::hcc878ea466fc238e
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/backtrace.rs:154:18
  65:     0x5972006024f2 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h0f21581fed62fed9
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/mod.rs:522:17
  66:     0x5972006024f2 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf4b9a69eb8a59727
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/panic/unwind_safe.rs:272:9
  67:     0x5972006024f2 - std::panicking::try::do_call::h8359e72234817fb1
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:557:40
  68:     0x5972006024f2 - std::panicking::try::h2ea46e2b37d7da99
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panicking.rs:520:19
  69:     0x5972006024f2 - std::panic::catch_unwind::hd34da2dfe227df81
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/panic.rs:345:14
  70:     0x5972006024f2 - std::thread::Builder::spawn_unchecked_::{{closure}}::heb6dbe2d3dba7ae2
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/thread/mod.rs:521:30
  71:     0x5972006024f2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h60982394cbbf2b6e
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/core/src/ops/function.rs:250:5
  72:     0x5972006a22db - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h04f4c6e173ad22b3
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/alloc/src/boxed.rs:2230:9
  73:     0x5972006a22db - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h206d75ac6ec19d83
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/alloc/src/boxed.rs:2230:9
  74:     0x5972006a22db - std::sys::pal::unix::thread::Thread::new::thread_start::hdd18e2f9323a466b
                               at /rustc/0609062a91c8f445c3e9a0de57e402f9b1b8b0a7/library/std/src/sys/pal/unix/thread.rs:105:17
  75:     0x7ecd8fbc839d - start_thread
                               at /usr/src/debug/glibc/glibc/nptl/pthread_create.c:447:8
  76:     0x7ecd8fc4d49c - __GI___clone3
                               at /usr/src/debug/glibc/glibc/misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  77:                0x0 - <unknown>
```

It's always worked fine for me up to this point. I just cloned and rebuilt from latest source and still getting it, so duly reporting.

**Comment by valentink-eroad** [comment]
Hi. I'm getting the similar (or the same) panic about `InvalidMonth` on rogcat release 0.5 running on Ubuntu 22.04:
```
08:11:28 ❯ RUST_BACKTRACE=full rogcat -M bt_
00:00:00.472                                (0 0)  D    calling  bt_init+0x0/0x94 @ 1
00:00:00.472                                (0 0)  D    initcall bt_init+0x0/0x94 returned 0 after 0 usecs
23:36:50.205                                (520 520)  E    The file .bt_nv.bin exist 0 ---9,remove it
23:36:50.375                                (520 520)  E  ┌ The file /persist/bluetooth/.bt_nv.bin doesn't ex
23:36:50.375                                (520 520)  E  └ ist or empty or addr is random 0...
thread 'tokio-runtime-worker-1' panicked at /home/vxxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rogcat-0.5.0/src/terminal.rs:184:57:
Date format error: InvalidMonth
stack backtrace:
   0:     0x5572eb24af4a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x5572eb272dd3 - core::fmt::write::h7550c97b06c86515
   2:     0x5572eb247403 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x5572eb24ad92 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x5572eb24bd3c - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x5572eb24bb82 - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x5572eb24c317 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   7:     0x5572eb24c1aa - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   8:     0x5572eb24b429 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
   9:     0x5572eb24be3c - rust_begin_unwind
  10:     0x5572eaec8f10 - core::panicking::panic_fmt::h0c3082644d1bf418
  11:     0x5572eaec92f6 - core::result::unwrap_failed::hd20b4aa073bda1e2
  12:     0x5572eaf10532 - <rogcat::terminal::Human as futures::sink::Sink>::start_send::h728fe7e8592cf3f5
  13:     0x5572eaf3bd40 - <futures::sink::map_err::SinkMapErr<S,F> as futures::sink::Sink>::start_send::h67c10ebe80cfabe1
  14:     0x5572eaf2ed83 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h7e24d52e3ab59f4c
  15:     0x5572eaf3c139 - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h120ad8617db5f6c1
  16:     0x5572eaf2fa3c - <futures::sync::oneshot::Execute<F> as futures::future::Future>::poll::hc8d43251d666ba33
  17:     0x5572eb1ad2cb - futures::task_impl::std::set::h9bc24d40eba79e07
  18:     0x5572eb1aa6ee - tokio_threadpool::task::Task::run::hbe510b13eb78d50d
  19:     0x5572eb1a768d - tokio_threadpool::worker::Worker::run_task::ha2d3a10921d796fc
  20:     0x5572eb1a6ad6 - tokio_threadpool::worker::Worker::run::heb9d60a929dc377d
  21:     0x5572eb191f5c - tokio_timer::clock::clock::with_default::ha7df392b7af5a425
  22:     0x5572eb193635 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h4d8b7515c9a2ee5f
  23:     0x5572eb1a6579 - tokio_threadpool::worker::Worker::do_run::h822e46c294bdd190
  24:     0x5572eb1aab2d - std::sys::backtrace::__rust_begin_short_backtrace::h262bb7217ec90e57
  25:     0x5572eb1b27f9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h624dfd3a1b0115b9
  26:     0x5572eb24ff6b - std::sys::pal::unix::thread::Thread::new::thread_start::hcc78f3943333fa94
  27:     0x795d56c94ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  28:     0x795d56d26850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  29:                0x0 - <unknown>
```

**Comment by flxo** [comment]
@sjuxax Thanks for the report. Can you please provide the raw log that includes the messages that confuses the parser?

**Comment by georgedorn** [comment]
I added some diagnostics to the point the error happens, and got this:
```
Error: InvalidMonth
Timestamp: Timestamp { tm: Tm { tm_sec: 31, tm_min: 6, tm_hour: 13, tm_mday: 2, tm_mon: 12, tm_year: 0, tm_wday: 0, tm_yday: 0, tm_isdst: 0, tm_utcoff: 0, tm_nsec: 413000000 } }
Format: %H:%M:%S.%f
Message: FATAL EXCEPTION: main
Raw line: 12-02 13:06:31.413 22207 22207 E AndroidRuntime: FATAL EXCEPTION: main
Tags: ["AndroidRuntime"]
Level: Error
```

And yeah, that's the very first entry for the month of December.

I tried updating the 'time' library, but 0.1.45 doesn't fix it, and 0.2.x has a different API.
